<?php

function simplify_content_form_alter(&$form, $form_state, $form_id) {
    if ($form_id){

        $form['menu']['#access'] = 0;
        $form['comment_settings']['#access'] = 0;
        $form['revision_information']['#access'] = 0;
        $form['path']['#access'] = 0;
        $form['options']['#access'] = 0;
        $form['author']['#access'] = 0;

        // print '<pre>';
        // print_r($form);
        // print '</pre>';
    }

}
// function simplify_content_menu_alter(&$items) {
//     print_r($items['node']['access_arguments']);
//     $items['node/add/news']['access callback'] = FALSE;
// }
